### ISSUE TITLE
Group chat doesn't showup

### ISSUE THREAD

**Issue by RoiArthurB** [mautrix/facebook#180]
Hello,

My group chat doesn't show up and display this error when I send a message on it (from Facebook) : 

```

Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]: [2021-10-11 09:29:54,065] [DEBUG@mau.portal.1481515808553265] Handling Facebook event mid.$gAAVDbkd_eTGCn_Utwl8bq_lCRtpt (/6853260345021487725)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]: [2021-10-11 09:29:54,102] [ERROR@mau.portal.1481515808553265] Error handling Facebook message mid.$gAAVDbkd_eTGCn_Utwl8bq_lCRtpt
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]: Traceback (most recent call last):
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 774, in handle_facebook_message
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     await self._handle_facebook_message(source, sender, message, reply_to)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 843, in _handle_facebook_message
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     event_ids = await self._handle_mqtt_message(source, intent, message, reply_to)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 871, in _handle_mqtt_message
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     event_ids.append(await self._handle_facebook_text(intent, message, reply_to,
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 1022, in _handle_facebook_text
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     return await self._send_message(intent, content, timestamp=timestamp)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/bridge/portal.py", line 82, in _send_message
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     return await intent.send_message_event(self.mxid, event_type, content, **kwargs)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 95, in wrapper
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     return await __method(*args, **kwargs)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 282, in send_message_event
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     return await super().send_message_event(room_id, event_type, content, **kwargs)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/client/api/events.py", line 314, in send_message_event
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     resp = await self.api.request(Method.PUT, url, content, **kwargs)
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     return await self._send(method, full_url, content, query_params, headers or {})
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 180, in _send
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]:     raise make_request_error(http_status=response.status,
Oct 11 16:29:54 osmc matrix-mautrix-facebook[19041]: mautrix.errors.request.MForbidden: Unknown room
```

In the same way, search for the group chat name doesn't work, nor trying to force the conversation (chatting with `@facebook_<CHAT_ID>:DOMAIN` ) :/ 

My installation is:
- from [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-facebook.md) 
  - self build on my Raspberry Pi 4
- Mautrix version 0.3.1
- Synapse version 1.44.0
if it can help 🤷

EDIT: Forgot to say, but everything works perfectly for Direct chat (double puppets, reaction, stickers, etc etc)

**Comment by RoiArthurB** [comment]
Don't know how, but fixed 🤷🤷🤷
