### ISSUE TITLE
Unable to receive images

### ISSUE THREAD

**Issue by Amcio** [mautrix/facebook#184]
Receiving any media results in the following error:

```
Handling Facebook event mid.$cAAAAANEW8rKCvqI0T18jVztIW0G3 (/6855418969916654007)
Error handling Facebook message mid.$cAAAAANEW8rKCvqI0T18jVztIW0G3
 Traceback (most recent call last):
 File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 774, in handle_facebook_message
    await self._handle_facebook_message(source, sender, message, reply_to)
   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 843, in _handle_facebook_message
   event_ids = await self._handle_mqtt_message(source, intent, message, reply_to)
   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 863, in _handle_mqtt_message
     attach_ids = await asyncio.gather(
File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 1047, in _handle_facebook_attachment
     content = await self._convert_mqtt_attachment(msg_id, source, intent, attachment,
   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 979, in _convert_mqtt_attachment
    mxc, additional_info, decryption_info = await self._reupload_fb_file(
   File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 238, in _reupload_fb_file
     url = await intent.upload_media(data, mime_type=upload_mime_type, filename=filename)
   File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
    return await __method(*args, **kwargs)
   File "/usr/lib/python3.9/site-packages/mautrix/client/api/modules/media_repository.py", line 58, in upload_media
     resp = await self.api.request(Method.POST, MediaPath.upload, content=data,
   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
     return await self._send(method, full_url, content, query_params, headers or {})
   File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 180, in _send
     raise make_request_error(http_status=response.status,
 mautrix.errors.request.MatrixUnknownRequestError: 404:
 <html>
  <head><title>404 - No Such Resource</title></head>
   <body>
     <h1>No Such Resource</h1>
     <p>Sorry. No luck finding that resource.</p>
   </body>
 </html>
```

**Comment by tulir** [comment]
That's a problem on your homeserver, probably that the homeserver URL configured in the bridge doesn't reach the media repo
