### ISSUE TITLE
Can't start Bridge since SQlite Feat.

### ISSUE THREAD

**Issue by DoM1niC** [mautrix/facebook#191]
Can't start Bridge since SQlite Feat.

```
[2021-11-09 04:57:06,135] [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/opt/matrix/bridges/matrix-appservice-facebook/lib/python3.9/site-packages/mautrix/util/program.py", line 93, in _prepare
    self.prepare()
  File "/opt/matrix/bridges/matrix-appservice-facebook/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 87, in prepare
    self.prepare_db()
  File "/opt/matrix/bridges/matrix-appservice-facebook/lib/python3.9/site-packages/mautrix_facebook/__main__.py", line 59, in prepare_db
    self.db = Database(self.config["appservice.database"], upgrade_table=upgrade_table,
```

**Comment by tulir** [comment]
That's not the full stack trace, but I'd guess your installation is somehow messed up

**Comment by olmari** [comment]
I got this after lates upgrade, we run psql..

```
marras 09 16:26:29 morpheus systemd[1]: Started Matrix-Facebook bridge bot.
marras 09 16:26:30 morpheus python[255045]: Traceback (most recent call last):
marras 09 16:26:30 morpheus python[255045]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
marras 09 16:26:30 morpheus python[255045]:     "__main__", mod_spec)
marras 09 16:26:30 morpheus python[255045]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
marras 09 16:26:30 morpheus python[255045]:     exec(code, run_globals)
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix_facebook/__main__.py", line 21, in <module>
marras 09 16:26:30 morpheus python[255045]:     from mautrix.bridge import Bridge
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/bridge/__init__.py", line 5, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .matrix import BaseMatrixHandler
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 45, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .e2ee import EncryptionManager
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/bridge/e2ee.py", line 17, in <module>
marras 09 16:26:30 morpheus python[255045]:     from mautrix.crypto import (OlmMachine, CryptoStore, StateStore, PgCryptoStore,
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/crypto/__init__.py", line 4, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .store import CryptoStore, StateStore, PgCryptoStore, MemoryCryptoStore
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/crypto/store/__init__.py", line 4, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .asyncpg import PgCryptoStore
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/crypto/store/asyncpg/__init__.py", line 1, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .store import PgCryptoStore
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/crypto/store/asyncpg/store.py", line 12, in <module>
marras 09 16:26:30 morpheus python[255045]:     from mautrix.util.async_db import Database
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/util/async_db/__init__.py", line 10, in <module>
marras 09 16:26:30 morpheus python[255045]:     from .aiosqlite import SQLiteDatabase
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/util/async_db/aiosqlite.py", line 59, in <module>
marras 09 16:26:30 morpheus python[255045]:     class SQLiteDatabase(Database):
marras 09 16:26:30 morpheus python[255045]:   File "/opt/facebookbot/lib/python3.7/site-packages/mautrix/util/async_db/aiosqlite.py", line 61, in SQLiteDatabase
marras 09 16:26:30 morpheus python[255045]:     _pool: asyncio.Queue[TxnConnection]
marras 09 16:26:30 morpheus python[255045]: TypeError: 'type' object is not subscriptable
marras 09 16:26:30 morpheus systemd[1]: facebookbot.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by olmari** [comment]
Running `pip uninstall aiosqlite` quickfixed behaviour for now.
