### ISSUE TITLE
Cannot send image to Facebook

### ISSUE THREAD

**Issue by waclaw66** [mautrix/facebook#195]
I got following exception while sending PNG image to Facebook...

```
lis 30 15:32:59 bolesiny python[2468606]: [2021-11-30 15:32:59,600] [INFO@aiohttp.access] ::1 [30/Nov/2021:14:32:59 +0000] "PUT /transactions/8218?access_token=[redacted] HTTP/1.1" 200 159 "-" "Synapse/1.47.1"
lis 30 15:32:59 bolesiny python[2468606]: [2021-11-30 15:32:59,601] [DEBUG@mau.mx] Received Matrix event $nMO6Nc3gUpqdp2CodT9jRVsPROgzL7aX29kiIfRXmlc from @waclaw:bolesiny.net in !euqiXFLCQUaPACEaVd:bolesiny.net
lis 30 15:32:59 bolesiny python[2468606]: --- Logging error ---
lis 30 15:32:59 bolesiny python[2468606]: Traceback (most recent call last):
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 576, in handle_matrix_message
lis 30 15:32:59 bolesiny python[2468606]:     await self._handle_matrix_message(sender, message, event_id)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 596, in _handle_matrix_message
lis 30 15:32:59 bolesiny python[2468606]:     await self._handle_matrix_media(event_id, sender, message)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 653, in _handle_matrix_media
lis 30 15:32:59 bolesiny python[2468606]:     resp = await sender.client.send_media(data, message.body, mime,
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/upload.py", line 75, in send_media
lis 30 15:32:59 bolesiny python[2468606]:     json_data = await self._handle_response(resp)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/base.py", line 202, in _handle_response
lis 30 15:32:59 bolesiny python[2468606]:     body = await resp.json()
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib64/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
lis 30 15:32:59 bolesiny python[2468606]:     raise ContentTypeError(
lis 30 15:32:59 bolesiny python[2468606]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://rupload.facebook.com/messenger_image/19a3088a68425de98f593d64e61058b9687145601571
1335263')
lis 30 15:32:59 bolesiny python[2468606]: During handling of the above exception, another exception occurred:
lis 30 15:32:59 bolesiny python[2468606]: Traceback (most recent call last):
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/logging/handlers.py", line 73, in emit
lis 30 15:32:59 bolesiny python[2468606]:     if self.shouldRollover(record):
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/logging/handlers.py", line 193, in shouldRollover
lis 30 15:32:59 bolesiny python[2468606]:     msg = "%s\n" % self.format(record)
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/logging/__init__.py", line 942, in format
lis 30 15:32:59 bolesiny python[2468606]:     return fmt.format(record)
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/logging/__init__.py", line 678, in format
lis 30 15:32:59 bolesiny python[2468606]:     record.message = record.getMessage()
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/logging/__init__.py", line 368, in getMessage
lis 30 15:32:59 bolesiny python[2468606]:     msg = msg % self.args
lis 30 15:32:59 bolesiny python[2468606]: TypeError: not all arguments converted during string formatting
lis 30 15:32:59 bolesiny python[2468606]: Call stack:
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
lis 30 15:32:59 bolesiny python[2468606]:     return _run_code(code, main_globals, None,
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
lis 30 15:32:59 bolesiny python[2468606]:     exec(code, run_globals)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/__main__.py", line 183, in <module>
lis 30 15:32:59 bolesiny python[2468606]:     MessengerBridge().run()
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/util/program.py", line 84, in run
lis 30 15:32:59 bolesiny python[2468606]:     self._run()
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/util/program.py", line 202, in _run
lis 30 15:32:59 bolesiny python[2468606]:     self.loop.run_until_complete(self._stop_task)
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/asyncio/base_events.py", line 628, in run_until_complete
lis 30 15:32:59 bolesiny python[2468606]:     self.run_forever()
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/asyncio/base_events.py", line 595, in run_forever
lis 30 15:32:59 bolesiny python[2468606]:     self._run_once()
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/asyncio/base_events.py", line 1881, in _run_once
lis 30 15:32:59 bolesiny python[2468606]:     handle._run()
lis 30 15:32:59 bolesiny python[2468606]:   File "/usr/lib64/python3.10/asyncio/events.py", line 80, in _run
lis 30 15:32:59 bolesiny python[2468606]:     self._context.run(self._callback, *self._args)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 204, in try_handle
lis 30 15:32:59 bolesiny python[2468606]:     await handler_func(event)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 602, in int_handle_event
lis 30 15:32:59 bolesiny python[2468606]:     await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix/bridge/matrix.py", line 347, in handle_message
lis 30 15:32:59 bolesiny python[2468606]:     await portal.handle_matrix_message(sender, message, event_id)
lis 30 15:32:59 bolesiny python[2468606]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 587, in handle_matrix_message
lis 30 15:32:59 bolesiny python[2468606]:     self.log.exception("Failed to handle matrix message.", e)
lis 30 15:32:59 bolesiny python[2468606]: Message: 'Failed to handle matrix message.'
lis 30 15:32:59 bolesiny python[2468606]: Arguments: (ContentTypeError(RequestInfo(url=URL('https://rupload.facebook.com/messenger_image/19a3088a68425de98f593d64e61058b96871456015711335263'), method='POST', headers=<CIMultiDictProxy('Host': 'rupload.facebook.com', 'x-fb-c
onnection-quality': 'EXCELLENT', 'x-fb-connection-type': 'WIFI', 'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 10; Pixel 3 Build/QQ3A.200605.001) [FBAN/Orca-Android;FBAV/294.0.0.24.129;FBPN/com.facebook.orca;FBLC/en_US;FBBV/263695262;FBCR/Verizon;FBMF/Google;FBBD/google;
FBDV/Pixel 3;FBSV/10;FBCA/arm64-v8a:null;FBDM/{density=2.75,width=1080,height=2028};FB_FW/1;]', 'x-tigon-is-retry': 'False', 'x-fb-http-engine': 'Liger', 'x-fb-client-ip': 'True', 'x-fb-connection-token': '[redacted]', 'x-fb-session-id': 'nid=WnryiQT
g4kVT;pid=Main;tid=3;nc=0;fc=0;bc=0,cid=04f52b0226e48799dbda576e5c1e5fc4', 'x-fb-sim-hni': '311390', 'x-fb-net-hni': '311390', 'authorization': 'OAuth [redacted]
WE0sA8pAddiL96oTw9RTtZCawfgDGNTrpXZBHB9JZCAEMVNs7PDIGQZDZD', 'app_id': '256002347743983', 'device_id': '6e5405c1-9c7d-4086-9b11-0f9ac3dc7462', 'attempt_id': '6871456015711335263', 'offset': '0', 'x-entity-length': '496601', 'x-entity-name': 'Snímek obrazovky 2021-11-30 15
3223.png', 'x-entity-type': 'image/png', 'content-type': 'application/octet-stream', 'client_tags': '{"trigger": "2:thread_list:thread", "is_in_chatheads": "false"}', 'original_timestamp': '1638282779637', 'x-fb-rmd': 'state=NO_MATCH', 'x-msgr-region': 'ODN', 'x-fb-friend
ly-name': 'post_resumable_upload_session', 'send_message_by_server': '1', 'sender_fbid': '100006344554306', 'to': '100000642065318', 'offline_threading_id': '6871456015711335263', 'ttl': '0', 'image_type': 'FILE_ATTACHMENT', 'Accept': '*/*', 'Accept-Encoding': 'gzip, defl
ate', 'Content-Length': '496601')>, real_url=URL('https://rupload.facebook.com/messenger_image/19a3088a68425de98f593d64e61058b96871456015711335263')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Conte
nt-Type': 'text/html; charset=utf-8', 'Date': 'Tue, 30 Nov 2021 14:32:59 GMT', 'Connection': 'close', 'Content-Length': '2959')>),)
l
```

**Comment by waclaw66** [comment]
Still doesn't work...
```
pro 21 23:25:18 python[1303797]: [2021-12-21 23:25:18,394] [INFO@aiohttp.access] ::1 [21/Dec/2021:22:25:18 +0000] "PUT /transactions/8488?access_token=[redacted] HTTP/1.1" 200 159 "-" "Synapse/1.49.2"
pro 21 23:25:18 python[1303797]: [2021-12-21 23:25:18,395] [DEBUG@mau.mx] Received Matrix event $A1bgL-tuZldZLpfNov3r7WdtkiasxCrifleWj7PBUkY from @waclaw:bolesiny.net in !euqiXFLCQUaPACxxxx:bolesiny.net
pro 21 23:25:18 python[1303797]: [2021-12-21 23:25:18,500] [ERROR@mau.portal.10000064206xxxx<->10000634455xxxx] Failed to handle Matrix message
pro 21 23:25:18 python[1303797]: Traceback (most recent call last):
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 578, in handle_matrix_message
pro 21 23:25:18 python[1303797]:     await self._handle_matrix_message(sender, message, event_id)
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 605, in _handle_matrix_message
pro 21 23:25:18 python[1303797]:     await self._handle_matrix_media(event_id, sender, message, is_relay)
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 677, in _handle_matrix_media
pro 21 23:25:18 python[1303797]:     resp = await sender.client.send_media(data, filename, mime, caption=caption,
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/upload.py", line 83, in send_media
pro 21 23:25:18 python[1303797]:     json_data = await self._handle_response(resp)
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib/python3.10/site-packages/maufbapi/http/base.py", line 229, in _handle_response
pro 21 23:25:18 python[1303797]:     body = await resp.json()
pro 21 23:25:18 python[1303797]:   File "/opt/mautrix-facebook/lib64/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
pro 21 23:25:18 python[1303797]:     raise ContentTypeError(
pro 21 23:25:18 python[1303797]: aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://rupload.facebook.com/messenger_image/25a7ce430cb34efc166980f355313ddb6879185022365877387')
pro 21 23:25:18 synapse[1244755]: synapse.logging.context: [PUT-56444] Re-starting finished log context PUT-56444
pro 21 23:25:18 python[1303797]: [2021-12-21 23:25:18,532] [INFO@aiohttp.access] ::1 [21/Dec/2021:22:25:18 +0000] "PUT /transactions/8489?access_token=[redacted] HTTP/1.1" 200 159 "-" "Synapse/1.49.2"
pro 21 23:25:19 synapse[1244755]: synapse.http.client: [GET-56455] Got 400 when downloading https://rupload.facebook.com/messenger_image/25a7ce430cb34efc166980f355313ddb6879185022365877387
pro 21 23:25:19 python[1303797]: [2021-12-21 23:25:19,324] [DEBUG@mau.user.@waclaw:bolesiny.net.@waclaw:bolesiny.net.mqtt] No handler for MQTT message in /t_trace: b'%\xca\x01\x19\x05\x00%\xa8\x01\x19\x05\x00\x00'
pro 21 23:25:19 python[1303797]: [2021-12-21 23:25:19,328] [DEBUG@mau.portal.10000064206xxxx<->10000634455xxxx] Handled Messenger read receipt from 10000634455xxxx up to 1640125519049/$fzoGlriLZUhbotxidhanm1cl7b9TDRGqO3n419fhIDQ
```
What could be the problem?

**Comment by waclaw66** [comment]
The bridge creates POST request to `https://rupload.facebook.com/messenger_image/25a7ce430cb34efc166980f355313ddb6879190528795144713` 
with headers
`{'x-fb-connection-quality': 'EXCELLENT', 'x-fb-connection-type': 'WIFI', 'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 11; Pixel 3 Build/RQ3A.211001.001) [FBAN/Orca-Android;FBAV/341.0.0.6.237;FBPN/com.facebook.orca;FBLC/en_US;FBBV/336996394;FBCR/Verizon;FBMF/Google;FBBD/google;FBDV/Pixel 3;FBSV/11;FBCA/arm64-v8a:null;FBDM/{density=2.75,width=1080,height=2028};FB_FW/1;]', 'x-tigon-is-retry': 'False', 'x-fb-http-engine': 'Liger', 'x-fb-client-ip': 'True', 'x-fb-server-cluster': 'True', 'x-fb-connection-token': '[redacted]', 'x-fb-session-id': 'nid=Bd5wk61TPv3E;pid=Main;tid=3;nc=0;fc=0;bc=0,cid=[redacted]', 'x-fb-sim-hni': '311390', 'x-fb-net-hni': '311390', 'x-fb-rmd': 'cached=0;state=NO_MATCH', 'authorization': 'OAuth [redacted]', 'accept-encoding': 'x-fb-dz;d=1, gzip, deflate', 'app_id': '256002347743983', 'device_id': '6e5405c1-9c7d-4086-9b11-0f9ac3dc7462', 'attempt_id': '6879190528795144713', 'offset': '0', 'x-entity-length': '233590', 'x-entity-name': 'Snímek obrazovky 2021-12-21 232223.jpg', 'x-entity-type': 'image/jpeg', 'content-type': 'application/octet-stream', 'client_tags': '{"trigger": "2:thread_list:thread", "is_in_chatheads": "false", "is_in_bubbles": "false"}', 'original_timestamp': '1640126831247', 'x-msgr-region': 'ODN', 'x-fb-friendly-name': 'post_resumable_upload_session', 'send_message_by_server': '1', 'sender_fbid': '10000634455xxxx', 'to': '10000064206xxxx', 'offline_threading_id': '6879190528795144713', 'ttl': '0', 'image_type': 'FILE_ATTACHMENT'}
`

and response is `400 Bad Request`

**Comment by JuniorJPDJ** [comment]
I'm having similar problem for some files.
