### ISSUE TITLE
Bridge @everyone and @silent

### ISSUE THREAD

**Issue by itsmeboy0** [mautrix/facebook#207]
Right now, messages with the `@everyone` and `@silent` tags are not bridged by the bridge.
![image](https://user-images.githubusercontent.com/75471378/147619985-b154f7aa-28f5-4d45-8bd9-8be2f55cc395.png)

**Comment by sumnerevans** [comment]
```
Traceback (most recent call last):
  File "/home/sumner/projects/beeper/mautrix/python/mautrix/types/util/serializable.py", line 101, in deserialize
    return cls(raw)
  File "/nix/store/40n9pd613v8fc3x39yjrgs1i7d4q8yl0-python3-3.10.4/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/nix/store/40n9pd613v8fc3x39yjrgs1i7d4q8yl0-python3-3.10.4/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 's' is not a valid MentionType
```

Should be easy to fix...
