### ISSUE TITLE
Bridge fails creating rooms for the first ~10 seconds after login

### ISSUE THREAD

**Issue by CarlAmbroselli** [mautrix/facebook#217]
After login the bridge logs a lot of the following errors:

```[2022-02-19 15:16:27,794] [DEBUG@mau.portal.100000691057941<->1671622904] Matrix room created: !redacted:redacted
[2022-02-19 15:16:27,827] [ERROR@mau.portal.100000691057941<->1671622904] Failed to create portal
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 233, in invite_user
    await super().invite_user(room_id, user_id, extra_content=extra_content)
  File "/usr/lib/python3.9/site-packages/mautrix/client/store_updater.py", line 85, in invite_user
    await super().invite_user(room_id, user_id, extra_content=extra_content)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 421, in invite_user
    await self.send_member_event(
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 392, in send_member_event
    content = await self.fill_member_event(room_id, user_id, content) or content
  File "/usr/lib/python3.9/site-packages/mautrix/client/store_updater.py", line 240, in fill_member_event
    profile = await self.get_profile(user_id)
  File "/usr/lib/python3.9/site-packages/mautrix/client/api/user_data.py", line 166, in get_profile
    content = await self.api.request(Method.GET, Path.profile[user_id])
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 359, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 256, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: Profile isn't available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 488, in create_matrix_room
    return await self._create_matrix_room(source, info)
  File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 605, in _create_matrix_room
    await self.main_intent.invite_user(
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 142, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 239, in invite_user
    raise IntentError(f"Failed to invite {user_id} to {room_id}", e)
mautrix.errors.base.IntentError: ('Failed to invite @carl:redacted to !redacted:matrix.carl-ambroselli.de', MForbidden("Profile isn't available"))
[2022-02-19 15:16:27,830] [DEBUG@mau.user.@carl:redacted.@carl:redacted] Syncing thread 1157799084243229
[2022-02-19 15:16:27,843] [DEBUG@mau.portal.1157799084243229] Creating Matrix room
[2022-02-19 15:16:27,845] [WARNING@mau.portal.1157799084243229] Got empty name in _update_name call
[2022-02-19 15:16:27,854] [INFO@aiohttp.access] 172.20.0.4 [19/Feb/2022:15:16:27 +0000] "PUT /transactions/91?access_token=redacted HTTP/1.1" 200 158 "-" "Synapse/1.52.0"
[2022-02-19 15:16:28,662] [DEBUG@mau.portal.1157799084243229] Not updating bridge info: no Matrix room created
```

After a while it seems to work, but I wonder if this skips a bunch of Facebook threads, because I do see a few logs like `Syncing thread 100002212511111` in between and these threads don't seem to re-appear later in that sync.

This seems to be thrown here: https://github.com/matrix-org/synapse/blob/bf60da1a60096fac5fb778b732ff2214862ac808/synapse/handlers/profile.py#L483-L491

**Comment by tulir** [comment]
Only happens with weird synapse configs, and was fixed in mautrix-python v0.14.7 anyway

**Comment by CarlAmbroselli** [comment]
I'm using the following configs:

```
require_auth_for_profile_requests: true
limit_profile_requests_to_users_who_share_rooms: true
federation_domain_whitelist:
  - <my-domain>
```

I found that the bump to matrix-python v0.14.7 isn't in the latest tag, when do you expect to cut the next release @tulir?

**Comment by CarlAmbroselli** [comment]
actually, I'll just disable `limit_profile_requests_to_users_who_share_rooms`
