### ISSUE TITLE
`raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e`

### ISSUE THREAD

**Issue by HammyHavoc** [mautrix/facebook#225]
This was working until this morning. On the latest docker container now, but still not working.

Get this in the log:

```
[2022-03-13 19:28:09,079] [[37mDEBUG[0m@[32mmau.user[0m.[33m@hammy:matrix.splitanatom.com[0m] Syncing thread 100016737616458
[2022-03-13 19:28:09,188] [[37mDEBUG[0m@[32mmau.user[0m.[33m@hammy:matrix.splitanatom.com.mqtt[0m] Connecting to Messenger MQTT
[2022-03-13 19:28:09,326] [[37mDEBUG[0m@[32mmau.user[0m.[33m@hammy:matrix.splitanatom.com.mqtt[0m] Re-creating sync queue after reconnect
[2022-03-13 19:28:09,334] [[37mDEBUG[0m@[32mmau.user[0m.[33m@hammy:matrix.splitanatom.com[0m] Sending bridge notice: Connected to Facebook Messenger
[2022-03-13 19:28:09,470] [[37mDEBUG[0m@[32mmau.portal[0m.[33m511537775678940[0m] Not backfilling 511537775678940: no most recent message found
[2022-03-13 19:28:09,470] [[37mDEBUG[0m@[32mmau.user[0m.[33m@mary:matrix.splitanatom.com[0m] Syncing thread 3037456012996101
[2022-03-13 19:28:09,527] [[33;1mWARNING[0m@[32mmau.user[0m.[33m@hammy:matrix.splitanatom.com[0m] Failed to send bridge notice
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 508, in ensure_joined
await self.join_room(room_id, max_retries=0)
File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 122, in wrapper
return await __method(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/mautrix/client/store_updater.py", line 62, in join_room
room_id = await super().join_room(
File "/usr/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 320, in join_room
content = await self.api.request(
File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 357, in request
return await self._send(method, full_url, content, query_params, headers or {})
File "/usr/lib/python3.9/site-packages/mautrix/api.py", line 250, in _send
raise make_request_error(
mautrix.errors.request.MUnknown: No known servers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/mautrix_facebook/user.py", line 657, in send_bridge_notice
event_id = await self.az.intent.send_message(await self.get_notice_room(), content)
File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 133, in wrapper
await __self.ensure_joined(room_id)
File "/usr/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 530, in ensure_joined
raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix.errors.base.IntentError: Failed to join room !MsnohXDJlYGRxgiUqT:matrix.splitanatom.com as @facebookbridge:matrix.splitanatom.com
```

Hoping someone can help as non-tech-literate family who are using Element/Matrix now can't talk via FB.

**Comment by tulir** [comment]
That's a warning, not an error. Probably caused either by a management room being deleted via the admin API, or the user kicking the bot and leaving the room.

**Comment by HammyHavoc** [comment]
Interesting, it just seemed to start working again out of the blue. Perhaps an FB issue or a problem elsewhere? Thanks for your help earlier via DM on Matrix BTW. :- )
