### ISSUE TITLE
Upgrade to 0.4.0 failed

### ISSUE THREAD

**Issue by hafx** [mautrix/facebook#235]
Hi,

I create this post to expose my issue because there are conflicts when I tried to upgrade from 0.3.3 to 0.4.0 

Mautrix-fb is installed/upgraded with pip. 

## How the bridge is updated : 
https://docs.mau.fi/bridges/python/setup/index.html?bridge=facebook
```
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
pip install --upgrade pip
pip install --upgrade setuptools
pip install --upgrade 'mautrix-facebook[all]'
```

## The error : 
```
Installing collected packages: mautrix
  Attempting uninstall: mautrix
    Found existing installation: mautrix 0.14.10
    Uninstalling mautrix-0.14.10:
      Successfully uninstalled mautrix-0.14.10
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
mautrix-facebook 0.3.3 requires mautrix<0.15,>=0.14.6, but you have mautrix 0.16.0 which is incompatible.
...
Installing collected packages: mautrix, mautrix-facebook
  Attempting uninstall: mautrix
    Found existing installation: mautrix 0.16.0
    Uninstalling mautrix-0.16.0:
      Successfully uninstalled mautrix-0.16.0
  Attempting uninstall: mautrix-facebook
    Found existing installation: mautrix-facebook 0.3.3
    Uninstalling mautrix-facebook-0.3.3:
      Successfully uninstalled mautrix-facebook-0.3.3
Successfully installed mautrix-0.15.8 mautrix-facebook-0.4.0

```

The bridge is not working since I upgraded to 0.4.0
What am I supposed to do ?

Thanks

**Comment by tulir** [comment]
That's not how you update the bridge, but it looks like pip managed to at least somewhat fix the dependencies you messed up, since the last line says successfully installed

**Comment by hafx** [comment]
Thanks for your answer. 
I create this issue because the bridge wont start : 

```
[2022-04-16 11:30:48,184] [CRITICAL@mau.init] Failed to initialize database
Traceback (most recent call last):
  File "/opt/mautrix-facebook/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 191, in start_db
    await self.db.start()
  File "/opt/mautrix-facebook/lib/python3.8/site-packages/mautrix/util/async_db/asyncpg.py", line 63, in start
    await super().start()
  File "/opt/mautrix-facebook/lib/python3.8/site-packages/mautrix/util/async_db/database.py", line 101, in start
    await self._check_foreign_tables()
  File "/opt/mautrix-facebook/lib/python3.8/site-packages/mautrix/util/async_db/database.py", line 109, in _check_foreign_tables
    raise ForeignTablesFound("found state_groups_state likely belonging to Synapse")
mautrix.util.async_db.errors.ForeignTablesFound: The database contains foreign tables (found state_groups_state likely belonging to Synapse)
[2022-04-16 11:30:48,187] [INFO@mau.init] You can use --ignore-foreign-tables to ignore this error
```
