### ISSUE TITLE
Multiple bridges in PostgreSQL database?

### ISSUE THREAD

**Issue by NielsVanderstraeten** [mautrix/facebook#257]
I have succesfully set-up my own Matrix Synapse homeserver with PostgreSQL database and have succesfully connected the mautrix-whatsapp bridge. However, when now attempting to set-up the mautrix-facebook bridge as well, I am presented with the following error during the last step of the installation.

How can I allow my PostgreSQL database, which is being used by Synapse, to be both available to mautrix-whatsapp and mautrix-facebook at the same time?

```(mautrix_facebook) root@debian:/etc/mautrix_facebook# python -m mautrix_facebook --ignore-foreign-tables
[2022-09-15 12:14:21,277] [INFO@mau.init] Initializing mautrix-facebook 0.4.0
[2022-09-15 12:14:21,279] [INFO@mau.init] Initialization complete in 0.08 seconds
[2022-09-15 12:14:21,279] [DEBUG@mau.init] Running startup actions...
[2022-09-15 12:14:21,279] [DEBUG@mau.init] Starting database...
[2022-09-15 12:14:21,279] [DEBUG@mau.db] Connecting to postgres://synapse_user:[password-redacted@localhost](mailto:password-redacted@localhost)/synapse
[2022-09-15 12:14:21,321] [CRITICAL@mau.init] Failed to initialize database
Traceback (most recent call last):
  File "/etc/mautrix_facebook/lib/python3.9/site-packages/mautrix/bridge/[bridge.py](http://bridge.py/)", line 191, in start_db
    await self.db.start()
  File "/etc/mautrix_facebook/lib/python3.9/site-packages/mautrix/util/async_db/[asyncpg.py](http://asyncpg.py/)", line 63, in start
    await super().start()
  File "/etc/mautrix_facebook/lib/python3.9/site-packages/mautrix/util/async_db/[database.py](http://database.py/)", line 103, in start
    await self._check_owner()
  File "/etc/mautrix_facebook/lib/python3.9/site-packages/mautrix/util/async_db/[database.py](http://database.py/)", line 124, in _check_owner
    raise DatabaseNotOwned(owner)
mautrix.util.async_db.errors.DatabaseNotOwned: The database is owned by mautrix-whatsapp
[2022-09-15 12:14:21,322] [INFO@mau.init] Sharing the same database with different programs is not supported

**Comment by tulir** [comment]
You can't. Create separate databases.

**Comment by NielsVanderstraeten** [comment]
I figured it out, for future reference:

1. Create a new PostgreSQL database (see [https://matrix-org.github.io/synapse/latest/postgres.html](url))
2. Set-up the mautrix-facebook bridge with the new database
3. Do not touch the Synapse homeserver.yaml file - only the original database needs to be referenced here.
