### ISSUE TITLE
log spammed with AssertionError

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/facebook#274]
```
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238941334Z [2022-12-09 17:00:50,238] [ERROR@mau.user.@X:juniorjpdj.pl] Failed to backfill portal X
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238981296Z Traceback (most recent call last):
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238987953Z   File "/usr/lib/python3.10/site-packages/mautrix_facebook/user.py", line 562, in _handle_backfill_requests_loop
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238992116Z     await portal.backfill(self, req)
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238996113Z   File "/usr/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 751, in backfill
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.238999986Z     last_message_timestamp = await self._backfill(source, backfill_request)
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.239003818Z   File "/usr/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 807, in _backfill
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.239007692Z     ) = await self.backfill_message_page(source, messages)
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.239011838Z   File "/usr/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 891, in backfill_message_page
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.239015625Z     assert self.first_event_id
matrix-mautrix-facebook-1  | 2022-12-09T17:00:50.239019149Z AssertionError
```

My log is spammed with messages like this (portal ID changes) and I suspect backfill is not happening in other chats due to that - I tried scheduling backfill on other chat and nothing happened in a few days.

**Comment by tulir** [comment]
Using MSC2716 backfill is currently not recommended, and it's not going to work on rooms created before the feature was added.
