### ISSUE TITLE
Own puppet joins rooms even when `invite_own_puppet_to_pm` is false

### ISSUE THREAD

**Issue by jzapataikono** [mautrix/facebook#281]
After upgrading the bridge from docker image tag `v0.4.1` to docker image `latest` the account puppet started to join all conversations despite `invite_own_puppet_to_pm` being in `false`. The puppet doesn't  join the room immediately, it joins the room after sending and receiving some messages, without following a pattern of time or amount of messages to join the room. 

Additionally we notice that just after the puppet joins the room it duplicates the last sent message and the next error is thrown:

```log
[2023-01-05 14:17:32,269] [DEBUG@mau.portal.654321<->12349876] @fb_12349876:darknet has read messages up to 1672873080053 -> $Oiyzyw634AL7cqOHYcJCwAFXGkD5QbqLGSkYdsiANMg
[2023-01-05 14:17:32,271] [DEBUG@mau.portal.654321<->12349876] 1/20 messages are after most recent message.
[2023-01-05 14:17:32,284] [INFO@mau.portal.654321<->12349876] Sending 1 new messages to !PqAzgCsBIHeAaWdUxV:darknet with batch ID None and previous event ID $CUiYKoHWZN9YHFl6IBeAVq0_0bdAJ0Il2jO9JhkWGV4
[2023-01-05 14:17:32,285] [DEBUG@mau.as.api.@fb_12349876:darknet] req #138: POST http://synapse:8008/_matrix/client/v3/join/%21PqAzgCsBIHeAaWdUxV%3Adarknet?user_id=@fb_12349876:darknet {}
[2023-01-05 14:17:32,363] [DEBUG@mau.user.@acd2:darknet.mqtt] Re-creating sync queue after reconnect
[2023-01-05 14:17:32,408] [DEBUG@mau.as.api.@fb_12349876:darknet] req #138 (/v3/join/%21PqAzgCsBIHeAaWdUxV%3Adarknet) completed in 122.4ms with status 200
[2023-01-05 14:17:32,415] [DEBUG@mau.as.api.@fb_12349876:darknet] req #139: PUT http://synapse:8008/_matrix/client/v3/rooms/%21PqAzgCsBIHeAaWdUxV%3Adarknet/send/m.room.message/mautrix-python_1672928252415013187_32?ts=1672928203100&user_id=@fb_12349876:darknet {"msgtype": "m.text", "body": "menubot1: \nHa sido un placer atenderte, gracias por comunicarte con nosotros \ud83d\ude0a", "format": "org.matrix.custom.html", "formatted_body": "menubot1: <br/>Ha sido un placer atenderte, gracias por comunicarte con nosotros \ud83d\ude0a"}
[2023-01-05 14:17:32,478] [DEBUG@mau.as] Handling transaction 15232 with 1 PDUs
[2023-01-05 14:17:32,479] [DEBUG@mau.as] Finished handling transaction 15232
[2023-01-05 14:17:32,479] [INFO@aiohttp.access] 172.18.0.5 [05/Jan/2023:14:17:32 +0000] "PUT /transactions/15232?access_token=**************************** HTTP/1.1" 200 159 "-" "Synapse/1.67.0"
[2023-01-05 14:17:32,581] [DEBUG@mau.as.api.@fb_12349876:darknet] req #139 (/v3/rooms/%21PqAzgCsBIHeAaWdUxV%3Adarknet/send/m.room.message/mautrix-python_1672928252415013187_32) completed in 166.4ms with status 200
[2023-01-05 14:17:32,584] [ERROR@mau.portal.654321<->12349876] Failed to store batch message IDs
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 1074, in _finish_batch
    await DBMessage.bulk_insert(messages)
  File "/usr/lib/python3.10/site-packages/mautrix_facebook/db/message.py", line 155, in bulk_insert
    await conn.copy_records_to_table("message", records=records, columns=columns)
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
    ret = await func(self, arg, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 151, in copy_records_to_table
    return await self.wrapped.copy_records_to_table(
  File "/usr/lib/python3.10/site-packages/asyncpg/connection.py", line 983, in copy_records_to_table
    return await self._protocol.copy_in(
  File "asyncpg/protocol/protocol.pyx", line 529, in copy_in
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "message_fb_txn_id_fb_sender_fb_receiver_index_key"
DETAIL:  Key (fb_txn_id, fb_sender, fb_receiver, index)=(7016769453099019260, 12349876, 12349876, 0) already exists.
[2023-01-05 14:17:32,594] [DEBUG@mau.user.@acd2:darknet] Thread sync is happening too quickly. Waiting for 4s
[2023-01-05 14:17:32,613] [DEBUG@mau.as] Handling transaction 15234 with 1 PDUs
[2023-01-05 14:17:32,613] [DEBUG@mau.as] Finished handling transaction 15234
[2023-01-05 14:17:32,614] [INFO@aiohttp.access] 172.18.0.5 [05/Jan/2023:14:17:32 +0000] "PUT /transactions/15234?access_token=**************************** HTTP/1.1" 200 159 "-" "Synapse/1.67.0"

```

**Comment by tulir** [comment]
That's expected if you enable backfill and don't set up `double_puppet_backfill`
