### ISSUE TITLE
Unable to recover from: "Your message may not have been bridged: This thread is disabled"

### ISSUE THREAD

**Issue by ferdinandyb** [mautrix/facebook#328]
With one particular user I started to get the above error message. I can still interact with this user in group chats, only direct messaging is down and only for this user. I tried deleting and unportalling the room, but nothing worked. I can still message the user directly with fb messenger. These are the logs I see when I try to write to the room:

```
synapse             | 2023-12-17 12:11:24,443 - synapse.access.http.8008 - 465 - INFO - GET-551192 - 89.223.195.250 - 8008 - {@ferdinandyb:matrix.ferdinandy.com} Processed request: 0.288sec/0.004sec (0.003sec, 0.002sec) (0.008sec/0.090sec/4) 1304B 200 "GET /_matrix/client/v3/sync?filter=4&timeout=30000&set_presence=online&since=s412482_1447569_4553_231830_238900_117_2541_38645_0_51 HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.51 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36" [0 dbevts]
mautrix-facebook    | [2023-12-17 12:11:24,449] [DEBUG@mau.as] Finished handling transaction 1829868
mautrix-facebook    | [2023-12-17 12:11:24,450] [INFO@aiohttp.access] 172.23.0.7 [17/Dec/2023:12:11:24 +0000] "PUT /_matrix/app/v1/transactions/1829868 HTTP/1.1" 200 159 "-" "Synapse/1.97.0"
synapse             | 2023-12-17 12:11:24,450 - synapse.http.client - 413 - INFO - as-sender-24957 - Received response to PUT http://mautrix-facebook:29319/_matrix/app/v1/transactions/1829868: 200
mautrix-facebook    | [2023-12-17 12:11:24,456] [DEBUG@mau.mx] Received Matrix event $6BreEEOCLw-dAMuUR8KBVcsYTEFYf1E8PjEUrpwuz48 from @ferdinandyb:matrix.ferdinandy.com in !pFnyqindkesBUvQVzk:matrix.ferdinandy.com
synapse             | 2023-12-17 12:11:24,573 - synapse.access.http.8008 - 465 - INFO - GET-551194 - 89.223.195.250 - 8008 - {None} Processed request: 0.003sec/0.000sec (0.001sec, 0.000sec) (0.000sec/0.001sec/2) 97B 200 "GET /_matrix/client/v3/profile/%40ferdinandyb%3Amatrix.ferdinandy.com HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.51 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36" [0 dbevts]
mautrix-facebook    | [2023-12-17 12:11:24,666] [DEBUG@mau.user.@ferdinandyb:matrix.ferdinandy.com.mqtt] Request publish to /t_sm queued, waiting for response SEND_MESSAGE_RESP
mautrix-facebook    | [2023-12-17 12:11:24,740] [DEBUG@mau.portal.500304534<->100000197444037] Error handling Matrix message $6BreEEOCLw-dAMuUR8KBVcsYTEFYf1E8PjEUrpwuz48: This thread is disabled
synapse             | 2023-12-17 12:11:24,757 - synapse.access.http.8008 - 465 - INFO - POST-551198 - 89.223.195.250 - 8008 - {@ferdinandyb:matrix.ferdinandy.com} Processed request: 0.069sec/0.007sec (0.005sec, 0.004sec) (0.001sec/0.036sec/3) 4881B 200 "POST /_matrix/client/v3/keys/query HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.51 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36" [0 dbevts]
mautrix-facebook    | [2023-12-17 12:11:24,742] [ERROR@mau.portal.500304534<->100000197444037] Failed to handle Matrix event $6BreEEOCLw-dAMuUR8KBVcsYTEFYf1E8PjEUrpwuz48
mautrix-facebook    | Traceback (most recent call last):
mautrix-facebook    |   File "/usr/lib/python3.11/site-packages/mautrix_facebook/portal.py", line 1318, in handle_matrix_message
mautrix-facebook    |     await self._handle_matrix_message(sender, message, event_id)
mautrix-facebook    |   File "/usr/lib/python3.11/site-packages/mautrix_facebook/portal.py", line 1342, in _handle_matrix_message
mautrix-facebook    |     await self._handle_matrix_text(event_id, sender, message)
mautrix-facebook    |   File "/usr/lib/python3.11/site-packages/mautrix_facebook/portal.py", line 1386, in _handle_matrix_text
mautrix-facebook    |     raise Exception(resp.error_message)
mautrix-facebook    | Exception: This thread is disabled
mautrix-facebook    | [2023-12-17 12:11:25,033] [DEBUG@mau.as.api.@facebook_500304534:matrix.ferdinandy.com] req #8360: PUT http://synapse:8008/_matrix/client/v3/rooms/%21pFnyqindkesBUvQVzk%3Amatrix.ferdinandy.com/send/m.room.message/mautrix-python_1702815084958957713_3482?user_id=@facebook_500304534:matrix.ferdinandy.com {"msgtype": "m.notice", "body": "\u26a0 Your message may not have been bridged: This thread is disabled"}
```

When I write on facebook, I see no logs on the matrix side. Since everything else works and has worked for a long time, I don't think this is a configuration issue, and I have no clue how to recover from this.

**Comment by tibu** [comment]
I experience the same issue lately with one user. I tried the same methods but nothing helped.

**Comment by RNLFoof** [comment]
I assume this is because of the new end to end encryption that messenger has now. I have a couple of chats that stopped bringing right under this message: 
![Screenshot_20240101_140135_Messenger](https://github.com/mautrix/facebook/assets/24951381/f5aa1088-04d6-4b6c-b24a-1c51819460e5)
